### PR TITLE
GenEntryContent with parametrised content

### LINKED ISSUE #100: Out of file descriptors!
When packing too many "big" files, `packFileEntry'` may lead to FD starvation. That's because it uses lazy I/O.

This happened in cabal-install when packing haddock generated documentation: see https://gitlab.haskell.org/ghc/ghc/-/issues/25172#note_630488

## How to reproduce

Try to pack N+1 "big" files with `ulimit -n N`

### PR DESCRIPTION
**Pull request by phadej**
See https://github.com/haskell/tar/issues/100#issuecomment-3215296134

### CODE REVIEW

**Comment by Bodigrim** [comment]
The direction looks good to me. Thanks, waiting until it becomes not a work-in-progress.

**Comment by phadej** [comment]
This is ready for review, every piece is in place, but I would rather not spend time polishing at this point, before its agreed this is *the* way forward.

File: Codec/Archive/Tar/Write.hs [hunk 1]
```diff
@@ -39,6 +43,16 @@ import qualified "os-string" System.OsString.Posix as PS
 write :: [Entry] -> LBS.ByteString
 write es = LBS.concat $ map putEntry es ++ [LBS.replicate (512*2) 0]
 
+write' :: [GenEntry OsPath TarPath LinkTarget] -> IO LBS.ByteString
```
Comment (Bodigrim) [inline Codec/Archive/Tar/Write.hs:49]: I wonder if this function should rather take a `Handle` and just write it, instead of returning `LBS.ByteString`.

File: Codec/Archive/Tar/Write.hs [hunk 2]
```diff
@@ -39,6 +43,16 @@ import qualified "os-string" System.OsString.Posix as PS
...
+write' es = interleavedByteStringConcat $ map putEntry' es ++ [pure $ LBS.replicate (512*2) 0]
+
+interleavedByteStringConcat :: [IO LBS.ByteString] -> IO LBS.ByteString
+interleavedByteStringConcat [] = return LBS.empty
```
Comment (Bodigrim) [inline Codec/Archive/Tar/Write.hs:53]: Could it be expressed via `foldr`, similar to `Codec.Archive.Tar.Pack.interleavedSequence`?

File: Codec/Archive/Tar/Write.hs [hunk 3]
```diff
@@ -59,6 +73,23 @@ putEntry entry = case entryContent entry of
     padding size = LBS.replicate paddingSize 0
       where paddingSize = fromIntegral (negate size `mod` 512)
 
+putEntry' :: GenEntry OsPath TarPath LinkTarget -> IO LBS.ByteString
+putEntry' entry' = do
+  entryContent' <- case entryContent entry' of
+    NormalFile path size -> do
+      content <- defaultRead size path
+      return $ NormalFile content size
```
Comment (Bodigrim) [inline Codec/Archive/Tar/Write.hs:84]: FWIW feel free to use `pure` instead of `return` in all new code, if you like.

File: Codec/Archive/Tar/Write.hs [hunk 4]
```diff
@@ -12,17 +12,21 @@
 -- Portability :  portable
 --
 -----------------------------------------------------------------------------
-module Codec.Archive.Tar.Write (write) where
+module Codec.Archive.Tar.Write (write, write') where
```
Comment (Bodigrim) [inline Codec/Archive/Tar/Write.hs:15]: We probably want to change `Codec.Archive.Tar.create` to use `pack'` and `write'` instead of `pack` and `write`.

File: Codec/Archive/Tar/Pack.hs [hunk 5]
```diff
@@ -181,6 +202,59 @@ packFileEntry' filepath tarpath = do
...
+  -> OsPath  -- ^ Full path to find the file on the local disk
+  -> tarPath -- ^ Path to use for the tar 'GenEntry' in the archive
+  -> IO (GenEntry content tarPath linkTarget)
+packFileEntryWithRead' r filepath tarpath = do
+  mtime   <- getModTime filepath
+  perms   <- getPermissions filepath
+  -- Get file size without opening it.
+  approxSize <- getFileSize filepath
+  content <- r (fromInteger approxSize) filepath
+  let size = fromIntegral approxSize
```
Comment (Bodigrim) [inline Codec/Archive/Tar/Pack.hs]: Can we cast `approxSize` only once?

File: Codec/Archive/Tar/Pack.hs [hunk 6]
```diff
@@ -181,6 +202,59 @@ packFileEntry' filepath tarpath = do
...
+  -> OsPath
+  -> IO BL.ByteString
+defaultRead approxSize filepath = do
+  if approxSize < 131072
+    -- If file is short enough, just read it strictly
+    -- so that no file handle dangles around indefinitely.
+    then do
+      cnt <- readFile' filepath
+      if fromIntegral (B.length cnt) /= approxSize
+      then fail "wrong size"
```
Comment (Bodigrim) [inline Codec/Archive/Tar/Pack.hs]: We probably need to generate a more detailed error message.

**Review by Bodigrim — COMMENTED** [review]
I'm content with the direction here and have only a few comments. To be sure, let's wait until the next weekend just in case someone suddenly comes up with a different, less invasive solution (or finds a fatal flaw in this approach).

File: Codec/Archive/Tar/Write.hs (hunk 1 above)
Comment (phadej) [reply Codec/Archive/Tar/Write.hs:49]: `cabal-install` does `GZip.compress` before writing

File: Codec/Archive/Tar/Write.hs (hunk 4 above)
Comment (phadej) [reply Codec/Archive/Tar/Write.hs:15]: Outside of the scope. `cabal-install` doesnt use `create`.

File: Codec/Archive/Tar/Write.hs (hunk 2 above)
Comment (phadej) [reply Codec/Archive/Tar/Write.hs:53]: I don't know. I find `foldr` version of `interleavedSequence` quite hard to grasp. The `(f . ) . g)` is IMO point-free taken too far.

File: Codec/Archive/Tar/Write.hs (hunk 3 above)
Comment (phadej) [reply Codec/Archive/Tar/Write.hs:84]: Do you mean I **SHOULD** use `pure`? I generally use `return` in `do` notation and `pure` otherwise, but I'm not applying that rule consistently for sure.

File: Codec/Archive/Tar/Pack.hs (hunk 6 above)
Comment (phadej) [reply Codec/Archive/Tar/Pack.hs]: the question is really, should this be an own exception in this case, or is reusing `IOError` fine. `tar` has a set of own `Exception`s.

File: Codec/Archive/Tar/Write.hs (hunk 3 above)
Comment (Bodigrim) [reply Codec/Archive/Tar/Write.hs:84]: You MAY use `pure` consistently or inconsistently, I do not mind either way.

File: Codec/Archive/Tar/Pack.hs (hunk 6 above)
Comment (Bodigrim) [reply Codec/Archive/Tar/Pack.hs]: If the file system is shifting under our feet, we can get all sorts of I/O exceptions from `readFile'` already. IMO size mismatch falls into the same category, so reusing `IOError` is good enough.

File: Codec/Archive/Tar/Pack.hs [hunk 7]
```diff
@@ -74,20 +78,38 @@ pack
...
 pack = packAndCheck (const Nothing)
 
+-- | 'pack'' is like 'pack', but doesn't read the contents of files,
+-- only creating entries with 'OsPath' as contents.
+--
+-- @since 0.7.0.0
+pack'
+  :: FilePath
+  -> [FilePath]
+  -> IO [GenEntry OsPath TarPath LinkTarget]
```
Comment (Bodigrim) [inline Codec/Archive/Tar/Pack.hs:88]: Given that we are going for a major version bump anyway, maybe it's time to switch from `FilePath` to `OsPath` everywhere... Although one can argue that `GenEntry OsPath` is a detail implementation and should be semi-hidden behind a type synonym...

(Not asking you to change anything, just thinking aloud)

**Review by Bodigrim — APPROVED** [review]
LGTM, thanks!

If there are no other comments or suggestions, I'll merge it on Sunday (feel free to remind me if I forget).

**Comment by Bodigrim** [comment]
Thanks a lot!
